export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const MARKET_ROUTE = "/market"
export const PRODUCT_ROUTE = "/product"